# Generated by Django 4.2.1 on 2023-05-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RNI', '0005_subscriptionid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionId',
            new_name='Subscription',
        ),
    ]
