# Generated by Django 4.2.1 on 2023-08-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNI', '0006_rename_subscriptionid_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFilterCriteriaAssocHoAssociateId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterCriteriaAssocHo_associateId', models.CharField(default='unverified', max_length=64)),
                ('filterCriteriaAssocHo_associateId_index', models.CharField(default='unverified', max_length=64)),
                ('filterCriteriaAssocHo_associateId_type', models.CharField(default='unverified', max_length=64)),
                ('filterCriteriaAssocHo_associateId_value', models.CharField(default='unverified', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionFilterCriteriaAssocHoEcgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterCriteriaAssocHo_ecgi', models.CharField(default='unverified', max_length=64)),
                ('filterCriteriaAssocHo_ecgi_index', models.CharField(default='unverified', max_length=64)),
                ('filterCriteriaAssocHo_ecgi_cellId', models.CharField(default='unverified', max_length=64)),
                ('filterCriteriaAssocHo_ecgi_plmn_mcc', models.CharField(default='unverified', max_length=64)),
                ('filterCriteriaAssocHo_ecgi_plmn_mnc', models.CharField(default='unverified', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionFilterCriteriaAssocHoHoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterCriteriaAssocHo_hoStatus', models.CharField(default='unverified', max_length=64)),
                ('filterCriteriaAssocHo_hoStatus_index', models.CharField(default='unverified', max_length=64)),
                ('filterCriteriaAssocHo_hoStatus_list', models.CharField(default='unverified', max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_Id',
            new_name='_links_description',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_type',
            new_name='_links_self_href',
        ),
        migrations.AddField(
            model_name='subscription',
            name='callbackReference',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiryDeadline_Seconds',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiryDeadline_nanoSeconds',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='filterCriteriaAssocHo_appInstanceId',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='filterCriteriaAssocHo_associateId',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='filterCriteriaAssocHo_description',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='filterCriteriaAssocHo_ecgi',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='filterCriteriaAssocHo_hoStatus',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='requestTestNotification',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriptionId',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriptionType',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='websockNotifConfig_description',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='websockNotifConfig_requestWebsocketUri',
            field=models.CharField(default='unverified', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='websockNotifConfig_websocketUri',
            field=models.CharField(default='unverified', max_length=64),
        ),
    ]
