# Generated by Django 4.2.1 on 2023-05-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RabInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_ins_id', models.CharField(default='unverified', max_length=64)),
                ('cell_id', models.CharField(default='unverified', max_length=64)),
                ('ue_ipv4_address', models.CharField(default='unverified', max_length=64)),
                ('ue_ipv6_address', models.CharField(default='unverified', max_length=64)),
                ('nated_ip_address', models.CharField(default='unverified', max_length=64)),
                ('gtp_teid', models.CharField(default='unverified', max_length=64)),
                ('erab_id', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('qci', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('erab_mbr_dl', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('erab_mbr_ul', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('erab_gbr_dl', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('erab_gbr_ul', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('appInstanceId', models.CharField(default='unverified', max_length=64)),
                ('cellId', models.CharField(default='unverified', max_length=64)),
                ('mcc', models.CharField(default='unverified', max_length=64)),
                ('mnc', models.CharField(default='unverified', max_length=64)),
                ('Type', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('value', models.CharField(default='unverified', max_length=64)),
                ('erabId', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('erabGbrDl', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('erabGbrUl', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('erabMbrDl', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('erabMbrUl', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('requestId', models.CharField(default='0', max_length=64)),
            ],
        ),
    ]
