# Generated by Django 4.2.1 on 2023-05-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='s1_bearer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_ue_id', models.CharField(default='unverified', max_length=64)),
                ('cellId', models.CharField(default='unverified', max_length=64)),
                ('enb_ipAddress', models.CharField(default='unverified', max_length=64)),
                ('enb_tunnelId', models.CharField(default='unverified', max_length=64)),
                ('sGw_ipAddress', models.CharField(default='unverified', max_length=64)),
                ('sGw_tunnelId', models.CharField(default='unverified', max_length=64)),
                ('mmec', models.CharField(default='unverified', max_length=64)),
                ('mtmsi', models.CharField(default='unverified', max_length=64)),
            ],
        ),
    ]
