# Generated by Django 4.2.1 on 2023-05-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RNI', '0002_s1_bearer_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='s1_bearer_info',
            new_name='s1bearerinfo',
        ),
    ]
