# Generated by Django 4.2.1 on 2023-05-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNI', '0003_rename_s1_bearer_info_s1bearerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer2meas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_ins_id', models.CharField(default='unverified', max_length=64)),
                ('cell_id', models.CharField(default='unverified', max_length=64)),
                ('dl_gbr_prb_usage_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_gbr_prb_usage_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('dl_nongbr_prb_usage_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_nongbr_prb_usage_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('dl_total_prb_usage_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_total_prb_usage_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('received_dedicated_preambles_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('received_randomly_selected_preambles_low_range_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('received_randomly_selected_preambles_high_range_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('number_of_active_ue_dl_gbr_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('number_of_active_ue_ul_gbr_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('number_of_active_ue_dl_nongbr_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('number_of_active_ue_ul_nongbr_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('dl_gbr_pdr_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_gbr_pdr_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('dl_nongbr_pdr_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_nongbr_pdr_cell', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('dl_gbr_delay_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_gbr_delay_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('dl_nongbr_delay_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_nongbr_delay_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('dl_gbr_pdr_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_gbr_pdr_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('dl_nongbr_pdr_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_nongbr_pdr_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('dl_gbr_throughput_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_gbr_throughput_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('dl_nongbr_throughput_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_nongbr_throughput_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('dl_gbr_data_volume_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_gbr_data_volume_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('dl_nongbr_data_volume_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('ul_nongbr_data_volume_ue', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
            ],
        ),
    ]
