# Generated by Django 4.2.1 on 2023-05-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RNI', '0004_layer2meas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_Id', models.CharField(default='unverified', max_length=64)),
                ('subscription_type', models.CharField(default='unverified', max_length=64)),
            ],
        ),
    ]
